export BROWSERSTACK_USERNAME="your_username"
export BROWSERSTACK_ACCESS_KEY="your_access_key"
export APP_USERNAME="app_username"
export APP_PASSWORD="app_password"
export BROWSERSTACK_BUILD_NAME="desired_build_name"
export BROWSERSTACK_PROJECT_NAME="desired_project_name"
